### ISSUE TITLE
Create Session Throwing Error

### ISSUE THREAD

**Issue by 91Abdullah** [squareetlabs/LaravelOpenVidu#13]
{"error":"curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE*"}

[2020-06-09 09:15:56] local.ERROR: curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE* {"userId":1,"exception":"[object] (ErrorException(code: 0): curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE* at C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php:59)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'curl_setopt_arr...', 'C:\\\\xampp\\\\htdocs...', 59, Array)
#1 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php(59): curl_setopt_array(Resource id #583, Array)
#2 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlHandler.php(39): GuzzleHttp\\Handler\\CurlFactory->create(Object(GuzzleHttp\\Psr7\\Request), Array)
#3 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#4 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#5 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\PrepareBodyMiddleware.php(66): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#6 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Middleware.php(29): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#7 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#8 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Middleware.php(57): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#9 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\HandlerStack.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#10 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(351): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(162): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#12 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(182): GuzzleHttp\\Client->requestAsync('post', Object(GuzzleHttp\\Psr7\\Uri), Array)
#13 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(95): GuzzleHttp\\Client->request('post', 'api/sessions', Array)
#14 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\squareetlabs\\laravel-openvidu\\src\\Session.php(72): GuzzleHttp\\Client->__call('post', Array)
#15 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\squareetlabs\\laravel-openvidu\\src\\Session.php(61): SquareetLabs\\LaravelOpenVidu\\Session->getSessionId()
#16 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\squareetlabs\\laravel-openvidu\\src\\OpenVidu.php(50): SquareetLabs\\LaravelOpenVidu\\Session->__construct(Object(GuzzleHttp\\Client), Object(SquareetLabs\\LaravelOpenVidu\\SessionProperties))
#17 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): SquareetLabs\\LaravelOpenVidu\\OpenVidu->createSession(Object(SquareetLabs\\LaravelOpenVidu\\SessionProperties))
#18 C:\\xampp\\htdocs\\conferenceAPI\\app\\Http\\Controllers\\ConferenceController.php(32): Illuminate\\Support\\Facades\\Facade::__callStatic('createSession', Array)
#19 [internal function]: App\\Http\\Controllers\\ConferenceController->createSession()
#20 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#21 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('createSession', Array)
#22 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\ConferenceController), 'createSession')
#23 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(196): Illuminate\\Routing\\Route->runController()
#24 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(685): Illuminate\\Routing\\Route->run()
#25 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#30 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#32 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#35 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#36 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#37 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#38 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 C:\\xampp\\htdocs\\conferenceAPI\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#56 C:\\xampp\\htdocs\\conferenceAPI\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#57 {main}
"}

**Comment by jcancig** [comment]
Hello @91Abdullah! This error you report is related to Guzzle, you can see it in this link

[https://github.com/guzzle/guzzle/issues/1413](https://github.com/guzzle/guzzle/issues/1413)

**Comment by 91Abdullah** [comment]
Dear @jcancig thanks for the help. Setting debug to false solved the issue.

**Comment by mehrzadminaie** [comment]
> Dear @jcancig thanks for the help. Setting debug to false solved the issue.

where should i set debug to false?
