### ISSUE TITLE
400 Error from token endpoint

### ISSUE THREAD

**Issue by alparslanahmed** [squareetlabs/LaravelOpenVidu#14]
When i am trying to make sample request to openvidu/token endpoint it gives a 400 error in clean installation.

![image](https://user-images.githubusercontent.com/5161926/89100782-c21e2500-d402-11ea-88ba-8a65092ece84.png)

**Comment by jcancig** [comment]
From what little I can see in the attached screenshot it looks like a problem with Guzzle and your server's 1.1/2 http configuration. To avoid the Guzzle log, please check the value of the debug variable in the configuration file and set it to false. Try again and if the error persists please send me the complete response. Thank you

**Comment by alparslanahmed** [comment]
Error persists with OPENVIDU_DEBUG=false here is my request and response:

`{
    "session": {
        "mediaMode": "ROUTED",
        "recordingMode": "MANUAL",
        "customSessionId": "alparslanahmed",
        "defaultOutputMode": "COMPOSED",
        "defaultRecordingLayout": "BEST_FIT",
        "defaultCustomLayout": "CUSTOM_LAYOUT"
    }
}`

`{
    "message": "Invalid response status code 400",
    "exception": "SquareetLabs\\LaravelOpenVidu\\Exceptions\\OpenViduException",
    "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/squareetlabs/laravel-openvidu/src/Session.php",
    "line": 80,
    "trace": [
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/squareetlabs/laravel-openvidu/src/Session.php",
            "line": 61,
            "function": "getSessionId",
            "class": "SquareetLabs\\LaravelOpenVidu\\Session",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/squareetlabs/laravel-openvidu/src/OpenVidu.php",
            "line": 50,
            "function": "__construct",
            "class": "SquareetLabs\\LaravelOpenVidu\\Session",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
            "line": 261,
            "function": "createSession",
            "class": "SquareetLabs\\LaravelOpenVidu\\OpenVidu",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/squareetlabs/laravel-openvidu/src/Http/Controllers/OpenViduController.php",
            "line": 30,
            "function": "__callStatic",
            "class": "Illuminate\\Support\\Facades\\Facade",
            "type": "::"
        },
        {
            "function": "token",
            "class": "SquareetLabs\\LaravelOpenVidu\\Http\\Controllers\\OpenViduController",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 239,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 196,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 685,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 687,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 662,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 628,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 617,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/fruitcake/laravel-cors/src/HandleCors.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/alparslanahmed/code/fitnessBackend/server.php",
            "line": 21,
            "function": "require_once"
        }
    ]
}`

**Comment by jcancig** [comment]
It's definitely something related to your configuration, it can be related to the http version, the Openvidu version and even the firewall. The error code 400 is returned by your OpenVidu instance. On my machine I can't reproduce the error, sorry

**Comment by alparslanahmed** [comment]
I am using OpenVidu Docker image and version 2.15.0

**Comment by alparslanahmed** [comment]
When i try with node example of OpenVidu everything works well. Problem is with Laravel.
