### ISSUE TITLE
Is there any way to unregister predefined routes?

### ISSUE THREAD

**Issue by yigit-serin** [squareetlabs/LaravelOpenVidu#6]
Hello,
Thank you for the great package, but is there any way to unregister predefined routes?

**Comment by jcancig** [comment]
Not currently, but I can get on it next week. Thank you so much for your input.

**Comment by stasoft91** [comment]
Hi there, any news about disabling or securing endpoints? Kinda seems like this package is intranet only for now.

Though it seems I can easily create 'MyOpenViduController extends OpenViduController' and force 404 on default routes.

**Comment by jcancig** [comment]
> Hi there, any news about disabling or securing endpoints? Kinda seems like this package is intranet only for now.
> 
> Though it seems I can easily create 'MyOpenViduController extends OpenViduController' and force 404 on default routes.

I have it on my roadmap but I'm having a lot of work these weeks
